### ISSUE TITLE
bug Discord login stop working

### ISSUE THREAD

**Issue by laggis** [Alexr03/TCAdminOAuth#1]
Hey so i have been using the discord login for a while and 2 days ago its just stop working and im getting this error.
![Untitled](https://user-images.githubusercontent.com/18127838/112115336-5a972e80-8bb9-11eb-9461-fcb62bf47a98.png)

**Comment by Daren-42** [comment]
Having a similar issue.
TCA Login screen will shoot me over to Discord.
I can log into Discord and select Authorize.
I'm redirected to the callback URL properly.
TCA shows the following error in the logs:

11/05/2022 16:43:15 System.Web.Mvc  System.InvalidOperationException: The view 'Error' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/[Template]/[NameSpace]/Service/Error.cshtml
~/Views/[Template]/[NameSpace]/OAuth/Error.cshtml
~/Views/[Template]/[NameSpace]/OAuth/Error.vbhtml
~/Views/[Template]/Shared/Error.cshtml
~/Views/[Template]/Shared/Error.vbhtml
   at System.Web.Mvc.ViewResult.FindView(ControllerContext context)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)

This is a fresh install of TCA and the SSO Module. I followed the directions and my configuration is setup as requested.
This happens when using both the TCAdmin NeXT and newest Discord V2 Theme.

**Comment by bombitmanbomb** [comment]
Having the same issue as above
